### ISSUE TITLE
Error in execution

### ISSUE THREAD

**Issue by nitinnew** [FelSiq/DBCV#1]
Hello!

I am encountering the following error while executing. Will be grateful if you may please check:-

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-5-18458eb2db9a>"](https://localhost:8080/#), line 6, in <cell line: 6>
    import dbcv

  File "/usr/local/lib/python3.10/dist-packages/dbcv/__init__.py", line 1, in <module>
    from .core import dbcv

  File "/usr/local/lib/python3.10/dist-packages/dbcv/core.py", line 35
    return arr[*np.meshgrid(inds_a, inds_b)]
               ^
SyntaxError: invalid syntax

**Comment by FelSiq** [comment]
Hi,

I was able to reproduce your error using Python 3.10. Weirdly enough, it hadn't happened when I tested using Python 3.11. I'll check the exact cause of this behavior, and upload a fix for this issue as soon as possible.

Thanks for letting me know about this issue,
Felipe.

**Comment by FelSiq** [comment]
I've done a quickfix to the main branch regarding this issue. Please install the updated version, and you should be good to go this time.

If the problem persists, or you encounter any other issue, please let me know.

Felipe.

**Comment by nitinnew** [comment]
Thanks for the prompt update. I was able to get it running.

I wanted to check if you have had a look at the implementation at https://github.com/christopherjenness/DBCV.
While your implementation is much faster, i am getting different DBCV score with both.
Would it be possible for you to have a look please?

**Comment by FelSiq** [comment]
Thanks for your response.

I indeed had looked into Christopher's implementation. In fact, it was that implementation that motivated me writing this package. In my opinion, that implementation was far too complex when compared to the original's paper description [1], isn't vectorized at all (hence why it is so slow), and I didn't quite understand how his implementation handle noise (or if it handled noise at all).

I'm aware that both implementation handle different results but, up to my personal interpretation of [1], I believe I followed correctly the description provided by the authors. Sadly, they don't provide an official implementation, so it's hard to tell apart who's right and who's wrong in this case.

I suggest you to take a look into [1], analyze both implementations (Christopher's and mine), and make your own conclusions. If you find any mistake in either implementation, please let us know.

Best regards,
Felipe.
 
---

[1] Moulavi, Davoud & Andretta Jaskowiak, Pablo & Campello, Ricardo & Zimek, Arthur & Sander, Joerg. (2014). Density-Based Clustering Validation. 10.1137/1.9781611973440.96.

**Comment by david-waterworth** [comment]
@FelSiq one difference between yours and Christopher's implementation is you seem to compute the full distance matrix upfront (using cdist) requiring O(n**2) memory, whilst Christopher's implementation appears to compute the distance from a point to (all?) neighbors - so I think it's probably O(n) memory but trades that off against speed.

I rapidly ran into out-of-memory on large datasets using your version - on the other hand Christopher's is quite slow.

**Comment by FelSiq** [comment]
Hello David.

Thanks for your feedback.

You are correct. My current implementation has a space complexity of
O(N**2).

Perhaps a way to mitigate this issue would be implementing a fall-back
computation method for larger datasets with lower space complexity,
although I'm not exactly sure how to do it efficiently (iterating over data
points in Python is unacceptable imo). I'm open to suggestions.

Best regards,
Felipe.


Em seg., 29 de abr. de 2024 às 01:38, David Waterworth <
***@***.***> escreveu:
